<?php

$title = "All Tabs";
$escaper = new Zend\Escaper\Escaper('utf-8');
$this->headTitle($title);

$i = 0;
$data = [];
foreach ($tabs as $tab) {
    $data[$i++] = $tab;
}

?>

<h1><?= $escaper->escapeHTML($title) ?></h1>

<hr>
<span class="text-center">Below is a view of what is in the db</span>
<hr>
<table class="table">
    <tr>
    <th>ID</th>
    <th>Slug</th>
    <th>Name</th>
    <th>Description</th>
    <th>Actions</th>
</tr>
<?php foreach ($data as $tab) : ?>
    <tr>
        <td><?= $escaper->escapeHtml($tab->id) ?></td>
        <td><?= $escaper->escapeHtml($tab->slug) ?></td>
        <td><?= $escaper->escapeHtml($tab->name) ?></td>
        <td><?= $escaper->escapeHtml($tab->description) ?></td>
        <td>
            <a href="<?= $this->url('tab', ['action' => 'edit', 'slug' => $tab->slug]) ?>">Edit</a>
            |
            <a class="post" href="<?= $this->url('tab', ['action' => 'delete', 'slug' => $tab->slug]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach;?>
</table>
<p>
    <a href="<?= $this->url('tab', ['action' => 'add']) ?>">Add new tab</a>
</p>
