<?php

$title = "All Group";
$escaper = new Zend\Escaper\Escaper('utf-8');
$this->headTitle($title);

$i = 0;
$data = [];
foreach ($groups as $group) {
    $data[$i++] = $group;
}

?>

<h1><?= $escaper->escapeHTML($title) ?></h1>

<hr>
<span class="text-center">Below is a view of what is in the db</span>
<hr>
<table class="table">
    <tr>
    <th>ID</th>
    <th>Slug</th>
    <th>Name</th>
    <th>Description</th>
    <th>Actions</th>
</tr>
<?php foreach ($data as $group) : ?>
    <tr>
        <td><?= $escaper->escapeHtml($group->id) ?></td>
        <td><?= $escaper->escapeHtml($group->slug) ?></td>
        <td><?= $escaper->escapeHtml($group->name) ?></td>
        <td><?= $escaper->escapeHtml($group->description) ?></td>
        <td>
            <a href="<?= $this->url('group', ['action' => 'edit', 'slug' => $group->slug]) ?>">Edit</a>
            |
            <a class="post" href="<?= $this->url('group', ['action' => 'delete', 'slug' => $group->slug]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach;?>
</table>
<p>
    <a href="<?= $this->url('group', ['action' => 'add']) ?>">Add new group</a>
</p>
