<?php

$title = "All Apps";
$escaper = new Zend\Escaper\Escaper('utf-8');
$this->headTitle($title);

?>

<h1><?= $escaper->escapeHTML($title) ?></h1>
<p>
    <a href="<?= $this->url('app', ['action' => 'add']) ?>">Add new app</a>
</p>

<table class="table">
    <tr>
    <th>Name</th>
    <th>URL</th>
    <th></th>
</tr>
<?php foreach ($apps as $app) : ?>
    <tr>
        <td><?= $escaper->escapeHtml($app->name) ?></td>
        <td><?= $escaper->escapeHtml($app->url) ?></td>
        <td>
            <a href="<?= $this->url('app', ['action' => 'edit', 'id' => $app->id]) ?>">Edit</a>
            <a href="<?= $this->url('app', ['action' => 'delete', 'id' => $app->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
