<?php

$title = "Tab";
$escaper = new Zend\Escaper\Escaper('utf-8');
$this->headTitle($title);

$i = 0;
$data = [];
foreach ($apps as $app) {
    $data[$i++] = $app;
}

?>

<?php
    $i = 0;
    $opened = false;
    foreach ($data as $app) :
        $i++;
        if ((($i-1) % 6) == 0 && !$opened) :
            echo "<div class='row'>";
        endif;
?>
        <div class="col-xs-6 col-sm-3 col-md-2">
            <div class="app-tile" id="app_<?= $escaper->escapeHtml($app->slug) ?>">
                <a href="<?= $this->url('app', ['action' => 'open', 'slug' => $app->slug]) ?>" target="_blank">
                    <img src="<?= $this->url('app', ['action' => 'icon', 'slug' => $app->slug]) .
                    "?v=" . (int) $app->version ?>" alt="">
                    <span class="app-name"><?= $escaper->escapeHtml($app->name) ?></span>
                </a>
            </div>
        </div>
<?php
        if ((($i) % 6) == 0 && $opened) :
            $opened = false;
            echo "</div>";
        else :
            $opened = true;
        endif;
    endforeach;
    if ($opened)
    {
        echo "</div>";
    }
?>
