<?php

$title = "Tab";
$escaper = new Zend\Escaper\Escaper('utf-8');
$this->headTitle($title);

$i = 0;
$data = [];
foreach ($apps as $app) {
    $data[$i++] = $app;
}

?>
<div class="row">
<?php
    foreach ($data as $app) :
?>
        <div class="col-4 col-sm-3 col-md-2">
          <a href="<?= $this->url('app', ['action' => 'open', 'slug' => $app->slug]) ?>" target="_blank">
            <div class="app-tile" id="app_<?= $escaper->escapeHtml($app->slug) ?>">
                    <img src="<?= $app->iconPath ?>" alt="">
                    <span class="app-name"><?= $escaper->escapeHtml($app->name) ?></span>
            </div>
          </a>
        </div>
<?php
    endforeach;
?>
</div>
