<?php

$title = "All Attributes";
$escaper = new Zend\Escaper\Escaper('utf-8');
$this->headTitle($title);

$i = 0;
$data = [];
foreach ($attributes as $attribute) {
    $data[$i++] = $attribute;
}

?>

<h1><?= $escaper->escapeHTML($title) ?></h1>

<hr>
<span class="text-center">Below is a view of what is in the db</span>
<hr>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Slug</th>
        <th>Name</th>
        <th>Data</th>
        <th>Description</th>
        <th>Actions</th>
    </tr>
<?php foreach ($data as $attribute) : ?>
    <tr>
        <td><?= $escaper->escapeHtml($attribute->id) ?></td>
        <td><?= $escaper->escapeHtml($attribute->slug) ?></td>
        <td><?= $escaper->escapeHtml($attribute->name) ?></td>
        <td><?= $escaper->escapeHtml($attribute->data) ?></td>
        <td><?= $escaper->escapeHtml($attribute->description) ?></td>
        <td>
            <a href="<?= $this->url('attribute', ['action' => 'edit', 'slug' => $attribute->slug]) ?>">Edit</a>
            |
            <a class="post" href="<?= $this->url('attribute', ['action' => 'delete', 'slug' => $attribute->slug]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach;?>
</table>
<p>
    <a href="<?= $this->url('attribute', ['action' => 'add']) ?>">Add new attribute</a>
</p>
