<?php
    use SessionManager\Session;
    use SessionManager\Tables;

    $tables = new Tables();
?>

<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(getenv('app_name'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/app.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/app.js?v=0.3.2'))
        ?>

        <script>
          // themeColor comes from the database group record
          // highlight/"lightened" and text colors are calculated based on
          //   lightness or darkness of the themeColor
          var myE = document.documentElement;
          var themeColor = "<?php echo $this->themeColor; ?>";
          myE.style.setProperty("--color-brand-primary", themeColor);

          // find intensity value of themeColor
            // break color value into RGB components
          var red = "0x" + themeColor.substr(1,2);
          var green = "0x" + themeColor.substr(3,2);
          var blue = "0x" + themeColor.substr(5,2);

          var redInt = parseInt(red);
          var greenInt = parseInt(green);
          var blueInt = parseInt(blue);
          var lumChange = 0.1;
          var textColor = "#ffffff";

          var intensity = (redInt*0.299 + greenInt*0.587 + blueInt*0.114);
          if (intensity > 186)
          {
            lumChange = -0.1;
            textColor = "#000000";
          } else if (intensity < 140)
          {
            lumChange = 0.5;
          }

          if (intensity > 49)
          {
            if (redInt > 231 || greenInt > 231 || blueInt > 231)
            {
              // if any one color component is high, darken instead of lighten
              lumChange = -0.2;
            }
            redInt = Math.round(Math.min(Math.max(0, redInt + (redInt * lumChange)), 255)).toString(16);
            greenInt = Math.round(Math.min(Math.max(0, greenInt + (greenInt * lumChange)), 255)).toString(16);
            blueInt = Math.round(Math.min(Math.max(0, blueInt + (blueInt * lumChange)), 255)).toString(16);
          }
          else
          {
            // extra help if the color is really dark (add absolute value instead of percentage)
            lumChange = 64;
            redInt = Math.round(Math.min(Math.max(0, redInt + lumChange), 255)).toString(16);
            greenInt = Math.round(Math.min(Math.max(0, greenInt + lumChange), 255)).toString(16);
            blueInt = Math.round(Math.min(Math.max(0, blueInt + lumChange), 255)).toString(16);
          }

          var lightenedColor = "#" +
            ("00" + redInt).substr(redInt.length) +
            ("00" + greenInt).substr(greenInt.length) +
            ("00" + blueInt).substr(blueInt.length);
          myE.style.setProperty("--color-brand-primary-lightened", lightenedColor);
          myE.style.setProperty("--color-brand-accent", textColor);

        </script>

    </head>
    <body>
        <header>
            <section>
                <div id="brand">
                    <a href="http://esucc.org" target="_blank">
                        <span id="logo" class="pull-left">
                            <img src="/images/esucc-logo-square.png" height="55" width="55" />
                        </span>
                        <span id="brandName" class="pull-left">
                            ESUCC
                        </span>
                    </a>
                </div>
                <div id="account-action" class="pull-right">
                    <?
                        include APPLICATION_PATH . '/module/Traits/partials/signin-out.php'
                    ?>
                </div>
            </section>
            <nav class="navbar navbar-inverse navbar-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <!--<a class="navbar-brand" href="<?= $this->url('home') ?>">App Launch Portal</a>-->
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <?
                                /*
                                 * For some reason the icon viewing the icon's causes
                                 * the layout's PHP to be processed. You can observe
                                 * this by uncommenting the following line.
                                 */
                                 note("URI: " . $_SERVER[REQUEST_URI]);

                                if (count($groups = Session::getGroups()) > 0)
                                foreach ($groups as $group) :
                            ?>
                                <!--<li class="nav_group"><?= $group->name ?></li>-->
                            <?
                                    foreach ($tables
                                        ->getTable('ownerTabs')
                                        ->getTabs($group->slug, [
                                            'type' => 'group'
                                            ]) as $tab) :
                            ?>
                                    <li class="nav_tab">
                                        <a href="<?= $this->url('tab', ['slug' => $tab->slug]) ?>">
                                            <?= $tab->name ?>
                                        </a>
                                    </li>

                            <?
                                    endforeach;
                                endforeach;
                            ?>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
