<?php
    use SessionManager\Session;
    use SessionManager\Tables;

    $tables = new Tables();
?>

<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(getenv('app_name'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/app.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/app.js?v=0.3.2'))
        ?>

        <script>
          // themeColor comes from the database group record
          // highlight/"lightened" and text colors are calculated based on
          //   lightness or darkness of the themeColor
          var myE = document.documentElement;
          var themeColor = "<?php echo $this->themeColor; ?>";
          myE.style.setProperty("--color-brand-primary", themeColor);

          // find intensity value of themeColor
            // break color value into RGB components
          var red = "0x" + themeColor.substr(1,2);
          var green = "0x" + themeColor.substr(3,2);
          var blue = "0x" + themeColor.substr(5,2);

          var redInt = parseInt(red);
          var greenInt = parseInt(green);
          var blueInt = parseInt(blue);
          var lumChange = 0.1;
          var textColor = "#ffffff";

          var intensity = (redInt*0.299 + greenInt*0.587 + blueInt*0.114);
          if (intensity > 186)
          {
            lumChange = -0.1;
            textColor = "#000000";
          }
          else if (intensity < 140)
          {
            lumChange = 0.5;
          }

          if (intensity > 49)
          {
            if (redInt > 231 || greenInt > 231 || blueInt > 231)
            {
              // if any one color component is high, darken instead of lighten
              lumChange = -0.2;
            }
            redInt = Math.round(Math.min(Math.max(0, redInt + (redInt * lumChange)), 255)).toString(16);
            greenInt = Math.round(Math.min(Math.max(0, greenInt + (greenInt * lumChange)), 255)).toString(16);
            blueInt = Math.round(Math.min(Math.max(0, blueInt + (blueInt * lumChange)), 255)).toString(16);
          }
          else
          {
            // extra help if the color is really dark (add absolute value instead of percentage)
            lumChange = 64;
            redInt = Math.round(Math.min(Math.max(0, redInt + lumChange), 255)).toString(16);
            greenInt = Math.round(Math.min(Math.max(0, greenInt + lumChange), 255)).toString(16);
            blueInt = Math.round(Math.min(Math.max(0, blueInt + lumChange), 255)).toString(16);
          }

          var lightenedColor = "#" +
            ("00" + redInt).substr(redInt.length) +
            ("00" + greenInt).substr(greenInt.length) +
            ("00" + blueInt).substr(blueInt.length);
          myE.style.setProperty("--color-brand-primary-lightened", lightenedColor);
          myE.style.setProperty("--color-brand-accent", textColor);

        </script>

    </head>
    <body>
        <header>
            <section>
                <div id="brand">
                  <span id="logo" class="float-left">
                      <img id="district-logo" src="/images/nebraskacloud-logo.png" height="55" />
                  </span>
                  <!-- <span id="brandName" class="pull-left">
                      ESUCC
                  </span> -->
                </div>
                <div id="account-action" class="float-right">
                    <?
                        include APPLICATION_PATH . '/module/Traits/partials/signin-out.php'
                    ?>
                </div>
            </section>
            <nav class="nav nav-tabs">
              <?
                  /*
                   * For some reason the icon viewing the icon's causes
                   * the layout's PHP to be processed. You can observe
                   * this by uncommenting the following line.
                   */
                   note("URI: " . $_SERVER[REQUEST_URI], 'debug');
                   foreach (Session::getGroups() as $group) {
                       if (empty($groupTabs = $group->getTabs())) continue;
                       foreach ($groupTabs as $tab) {
                           if (! Session::hasTabAccess($tab)) continue;
                           if ($tab->slug == $this->tabSlug) {
                               ?>
                               <a class="nav-link active" href="<?= $this->url('tab', ['slug' => $tab->slug]) ?>">
                                   <?= $tab->name ?>
                               </a>
                               <?
                           } else {
                               ?>
                               <a class="nav-link" href="<?= $this->url('tab', ['slug' => $tab->slug]) ?>">
                                   <?= $tab->name ?>
                               </a>
                               <?
                           }
                       }
                   }
                  if ($this->sudo)
                  {
                    if ($this->tabSlug == 'dashboard')
                    { ?>
                      <a class="nav-link active" href="<?= $this->url('dashboard') ?>">Admin</a>
                    <? }
                    else
                    { ?>
                      <a class="nav-link" href="<?= $this->url('dashboard') ?>">Admin</a>
                    <? }
                  }
              ?>
            </nav>
        </header>
        <div class="container">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
        <script>
          var logoFilename = "<?php echo $this->logoFilename; ?>";
          if (logoFilename.length > 1)
          {
            document.getElementById("district-logo").src= logoFilename;
          }
        </script>
    </body>
</html>
