<?php
    use SessionManager\Session;
    use SessionManager\Tables;

    $tables = new Tables();
?>

<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(getenv('app_name'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/app.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/app.js?v=0.3.2'))
        ?>
    </head>
    <body>
        <header>
            <section>
                <div id="brand">
                    <a href="http://esucc.org" target="_blank">
                        <span id="logo" class="float-left">
                            55px x 55px
                        </span>
                        <span id="brandName" class="float-left">
                            Sample Brand
                        </span>
                    </a>
                </div>
                <div id="account-action" class="float-right">
                    <?
                        include APPLICATION_PATH . '/module/Traits/partials/signin-out.php'
                    ?>
                </div>
            </section>
            <nav class="navbar navbar-expand-lg" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <!--<a class="navbar-brand" href="<?= $this->url('home') ?>">App Launch Portal</a>-->
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <?
                                /*
                                 * For some reason the icon viewing the icon's causes
                                 * the layout's PHP to be processed. You can observe
                                 * this by uncommenting the following line.
                                 */
                                 note("URI: " . $_SERVER[REQUEST_URI]);

                                if (count($groups = Session::getGroups()) > 0)
                                foreach ($groups as $group) :
                            ?>
                                <!--<li class="nav_group"><?= $group->name ?></li>-->
                            <?
                                    foreach ($tables
                                        ->getTable('ownerTabs')
                                        ->getTabs($group->slug, [
                                            'type' => 'group'
                                            ]) as $tab) :
                            ?>
                                    <li class="nav-item">
                                        <a href="<?= $this->url('tab', ['slug' => $tab->slug]) ?>">
                                            <?= $tab->name ?>
                                        </a>
                                    </li>

                            <?
                                    endforeach;
                                endforeach;
                            ?>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
