<?php

$title = "All Users";
$escaper = new Zend\Escaper\Escaper('utf-8');
$this->headTitle($title);

$i = 0;
$data = [];
foreach ($users as $user) {
    $data[$i++] = $user;
}

?>

<h1><?= $escaper->escapeHTML($title) ?></h1>

<hr>
<span class="text-center">Below is a view of what is in the db</span>
<hr>
<table class="table">
    <tr>
    <th>ID</th>
    <th>Slug</th>
    <th>Name</th>
    <th>Email</th>
    <th>Actions</th>
</tr>
<?php foreach ($data as $user) : ?>
    <tr>
        <td><?= $escaper->escapeHtml($user->id) ?></td>
        <td><?= $escaper->escapeHtml($user->slug) ?></td>
        <td><?= $escaper->escapeHtml($user->name) ?></td>
        <td><?= $escaper->escapeHtml($user->email) ?></td>
        <td>
            <a href="<?= $this->url('user', ['action' => 'edit', 'slug' => $user->slug]) ?>">Edit</a>
            |
            <a class="post" href="<?= $this->url('user', ['action' => 'delete', 'slug' => $user->slug]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach;?>
</table>
<p>
    <a href="<?= $this->url('user', ['action' => 'add']) ?>">Add new user</a>
</p>
