<?php

$title = "All Apps";
$escaper = new Zend\Escaper\Escaper('utf-8');
$this->headTitle($title);


$i = 0;
$data = [];
if ($apps)
{
  foreach ($apps as $app)
  {
    $data[$i++] = $app;
  }
}

?>
<div class="row">
<?php
    if ($portalError)
    {
      printf("<h2>%s</h2>", $portalErrorMessage);
    }

    foreach ($data as $app) :
?>
        <div class="col-4 col-sm-3 col-md-2">
          <a href="<?= $this->url('app', ['action' => 'open', 'slug' => $app->slug]) ?>" target="_blank">
            <div class="app-tile" id="app_<?= $escaper->escapeHtml($app->slug) ?>">
                                    <img src="<?= $app->iconPath ?>" alt="">
                    <span class="app-name"><?= $escaper->escapeHtml($app->name) ?></span>
            </div>
          </a>
        </div>
<?php
    endforeach;
?>
</div>
