<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Portal Test Info</h3>
            </div>
            <div class="panel-body">
                <p>
                   <?php if ($this->newSession)
                   {
                   	echo "New Session<br>";
                   }
                   else
                   {
                   	echo "Existing Session<br>";
                   }
                   echo "User ID: " . $this->userId;
                   echo "<br>Session Level: " . $this->sessionLevel;
                   echo "<br>Active Time: " . date("Y-m-d H:i:s", $this->activeTime); ?>
                </p>


            </div>
        </div>
    </div>
</div>

    <div class="row">
    <div class="col-md-2">
        <div class="app-tile">
            <img src="http://icons.iconarchive.com/icons/marcus-roberto/google-play/512/Google-Drive-icon.png">
            <div class="app-name">Google Drive</div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="app-tile">
            <img src="https://lh4.ggpht.com/-wROmWQVYTcjs3G6H0lYkBK2nPGYsY75Ik2IXTmOO2Oo0SMgbDtnF0eqz-BRR1hRQg=w300">
            <div class="app-name">Google Docs</div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="app-tile">
            <img src="https://logos.bugcrowdusercontent.com/logos/b71d/c1f5/1f8f12c4/a5e0c009d691e9be46fbcaed77c9cc4f_DO_Logo_icon_blue-larger.png">
            <div class="app-name">Digital Ocean</div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="app-tile">
            <img src="https://upload.wikimedia.org/wikipedia/commons/4/4e/Gmail_Icon.png">
            <div class="app-name">Gmail</div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="app-tile">
            <img src="https://www.unomaha.edu/news/img/0161-IMG_MDMW_UC_TERMINOLOGY2.jpg">
            <div class="app-name">UNOmaha</div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="app-tile">
            <img src="http://icons.iconarchive.com/icons/dakirby309/simply-styled/256/OS-Ubuntu-icon.png">
            <div class="app-name">Ubuntu</div>
        </div>
    </div>
</div>
